//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequintoBaldeonWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_EVENTOS_ARTISTAS
    {
        public decimal rea_codigo { get; set; }
        public decimal eve_codigo { get; set; }
        public decimal art_codigo { get; set; }
        public decimal for_codigo { get; set; }
        public Nullable<decimal> rea_precio_artista { get; set; }
        public Nullable<bool> rea_estado { get; set; }
        public string rea_observacion { get; set; }
    
        public virtual TARTISTAS TARTISTAS { get; set; }
        public virtual TEVENTOS TEVENTOS { get; set; }
        public virtual TFORMATOS TFORMATOS { get; set; }
    }
}
