//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequintoBaldeonWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARTISTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TARTISTAS()
        {
            this.R_ARTISTAS_PATROCINADORES = new HashSet<R_ARTISTAS_PATROCINADORES>();
            this.R_EVENTOS_ARTISTAS = new HashSet<R_EVENTOS_ARTISTAS>();
        }
    
        public decimal art_codigo { get; set; }
        public string art_nombres { get; set; }
        public string art_apellidos { get; set; }
        public string art_nombre_musical { get; set; }
        public Nullable<System.DateTime> art_fecha_lanzamiento { get; set; }
        public Nullable<System.DateTime> art_fecha_nac { get; set; }
        public Nullable<decimal> art_telefono { get; set; }
        public string art_email { get; set; }
        public string art_pagina_web { get; set; }
        public string art_facebook { get; set; }
        public string art_instagram { get; set; }
        public string art_tiktok { get; set; }
        public string art_youtube { get; set; }
        public string art_rrss { get; set; }
        public Nullable<int> art_tipo { get; set; }
        public Nullable<bool> art_estado { get; set; }
        public string art_observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ARTISTAS_PATROCINADORES> R_ARTISTAS_PATROCINADORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_EVENTOS_ARTISTAS> R_EVENTOS_ARTISTAS { get; set; }
    }
}
