//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequintoBaldeonWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFORMATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFORMATOS()
        {
            this.R_EVENTOS_ARTISTAS = new HashSet<R_EVENTOS_ARTISTAS>();
        }
    
        public decimal for_codigo { get; set; }
        public string for_detalle { get; set; }
        public Nullable<bool> for_estado { get; set; }
        public string for_observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_EVENTOS_ARTISTAS> R_EVENTOS_ARTISTAS { get; set; }
    }
}
