//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequintoBaldeonWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TPATROCINADORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPATROCINADORES()
        {
            this.R_ARTISTAS_PATROCINADORES = new HashSet<R_ARTISTAS_PATROCINADORES>();
        }
        [Display(Name = "Código")]
        [DisplayFormat(DataFormatString = "{0:F0}", ApplyFormatInEditMode = true)]
        public decimal pat_codigo { get; set; }
        public string pat_nombre { get; set; }
        public string pat_logo { get; set; }
        public string pat_email { get; set; }
        public string pat_telefono { get; set; }
        public string pat_direccion { get; set; }
        public string pat_pagina_web { get; set; }
        public string pat_rrss { get; set; }
        public Nullable<bool> pat_estado { get; set; }
        public string pat_observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ARTISTAS_PATROCINADORES> R_ARTISTAS_PATROCINADORES { get; set; }
    }
}
